CREATE TABLE students(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    FULLNAME VARCHAR NOT NULL,
    AGE SMALLINT NOT NULL,
    SEX VARCHAR NOT NULL,
    DEV_EXPERIENCE DOUBLE PRECISION,
    STATUS VARCHAR NOT NULL,
    mentor_id bigint
);
